services:
  web:
    container_name: web
    build:
      context: ./web
      target: ${NODE_ENV}
      args:
        - VITE_API_HOST=${API_HOST}
        - VITE_API_PORT=${API_PORT}
    depends_on:
      - api
    ports:
      - ${WEB_PORT}:${WEB_PORT}
    environment:
      - VITE_API_HOST=${API_HOST}
      - VITE_API_PORT=${API_PORT}
      - API_PORT=${API_PORT}
    volumes:
      - ./web:/app
      - web_node_modules:/app/node_modules
    networks:
      - external_net
      - internal_net
  api:
    container_name: api
    build:
      context: ./api
      target: ${GIN_MODE}
    depends_on:
      - db
    ports:
      - ${API_PORT}:${API_PORT}
    environment:
      - GIN_MODE=${GIN_MODE}
      - DB_PORT=${DB_PORT}
      - DB_HOST=${DB_HOST}
      - DB_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - ./api:/app
    networks:
      - internal_net

  db:
    container_name: db
    image: mysql:8.4.0
    restart: always
    ports:
      - ${DB_PORT}:${DB_PORT}
    environment:
      - MYSQL_PORT=${DB_PORT}
      - MYSQL_HOST=${DB_HOST}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - internal_net
volumes:
  web_node_modules:
  mysql_data:

networks:
  internal_net:
    internal: true
  external_net: